#pragma once
#include "lib/libtcod-1.16.0-alpha.15-x86_64-msvc/include/libtcod.h"
class Actor;
#include "Persistent.h"
#include "Destructible.h"
#include "Attacker.h"
#include "Ai.h"
#include "Pickable.h"
#include "Container.h"
#include "Actor.h"
#include "Map.h"
#include "Gui.h"
#include "Engine.h"
